#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

setup () {
  git stash > /dev/null
  git stash -u > /dev/null
  git stash pop -q stash@{1}
  git add . > /dev/null
}

cleanup () {
  git stash pop -q
}

setup

{ # try
  npx lint-staged &&
  npm run test -- --watchAll=false --coverage
} || { # catch
  cleanup
  exit 1
}

cleanup